#!/bin/bash

set -e

echo "🔍 Checking if 'uv' is installed..."

if ! command -v uv &> /dev/null; then
    echo "📦 'uv' not found. Installing..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.cargo/bin:$PATH"
else
    echo "✅ 'uv' is already installed."
fi

echo "🐍 Creating virtual environment with uv..."
uv sync


if [ "{{cookiecutter.initialize_git}}" == "yes" ]; then
    git init > /dev/null 2>&1
fi

if [ "{{cookiecutter.use_lsim}}" == "no" ]; then
    rm -rf apps/sms/
fi

source .venv/bin/activate
make format
